deployment:
  adservice: https://github.com/phu-phurithat/microservice-demo-adservice.git
  cartservice: https://github.com/phu-phurithat/microservice-demo-cartservice.git
  checkoutservice: https://github.com/phu-phurithat/microservice-demo-checkoutservice.git
  currencyservice: https://github.com/phu-phurithat/microservice-demo-currencyservice.git
  emailservice: https://github.com/phu-phurithat/microservice-demo-emailservice.git
  frontend: https://github.com/phu-phurithat/microservice-demo-frontend.git
  loadgenerator: https://github.com/phu-phurithat/microservice-demo-loadgenerator.git
  paymentservice: https://github.com/phu-phurithat/microservice-demo-paymentservice.git
  productcatalogservice: https://github.com/phu-phurithat/microservice-demo-productcatalogservice.git
  recommendationservice: https://github.com/phu-phurithat/microservice-demo-recommendationservice.git
  shippingservice: https://github.com/phu-phurithat/microservice-demo-shippingservice.git
  shoppingassistantservice: https://github.com/phu-phurithat/microservice-demo-shoppingassistantservice.git
